services:
  postgres:
    image: postgres:14
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432" # Optional: exposes Postgres to host at localhost:5432
    volumes:
      - pgdata_staging:/var/lib/postgresql/data
    networks:
      - postgres_network

  django:
    build:
      context: .
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: >
      sh -c "python manage.py migrate &&
            python manage.py shell -c 'from django.contrib.auth.models import User; User.objects.filter(username=\"${DJANGO_SUPERUSER_USERNAME}\").exists() or User.objects.create_superuser(\"${DJANGO_SUPERUSER_USERNAME}\", \"${DJANGO_SUPERUSER_EMAIL}\", \"${DJANGO_SUPERUSER_PASSWORD}\")' &&
            python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py collectstatic --noinput &&
            python manage.py runserver 0.0.0.0:8000"

    networks:
      - postgres_network
    volumes:
      - .:/app

  api:
    image: ghcr.io/gitinference/gitinference/fsdc-api:staging
    ports:
      - 5073:8000
    restart: always
    env_file:
      - .env
    networks:
      - postgres_network
    volumes:
      - files:/app/${MEDIA_ROOT}
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000

volumes:
  pgdata_staging:
  files:


networks:
  postgres_network:
    driver: bridge
